Repository jappe999/project-cards, pull requests merged in 2019-10, with the labels that each got.

#33 fix: Keep track of current round in session
  client/components/game/choose-cards.vue
  client/pages/game/_game/play.vue
  server/src/sessions/service/sessions.service.ts
  server/src/sessions/session.entity.ts
Labels: bug

#45 feat: List licenses used in this project
  README.md
  client/layouts/default.vue
  client/pages/license.vue
Labels: documentation, enhancement

#48 enhancement: increase blank space length
  client/components/game/playcard.vue
Labels: enhancement

#50 enhancement: use different font to improve look and feel
  .vscode/settings.json
  client/assets/css/tailwind.css
  client/assets/fonts/Open_Sans/LICENSE.txt
  client/assets/fonts/Open_Sans/OpenSans-Bold.ttf
  client/components/game/playcard.vue
  client/tailwind.config.js
Labels: enhancement

#56 feat: Share game
  client/components/share.vue
  client/pages/game/_game/play.vue
  client/tailwind.config.js
Labels: enhancement

#64 fix: use regex to lengthen all blank spaces
  client/components/game/playcard.vue
Labels: bug

#65 feat: Splash screen
  client/components/button/button.vue
  client/components/page/splash-screen.vue
  client/components/share.vue
  client/layouts/default.vue
  client/pages/index.vue
  client/pages/login.vue
  client/static/logo-animated.svg
  client/static/logo_animated.svg
  client/static/logo_v1.svg
  nuxt.config.ts
  package.json
Labels: enhancement

#67 fix: Redirect index to game
  client/pages/index.vue
  nuxt.config.ts
  package.json
  server/src/auth/controller/auth.controller.ts
  server/src/cards/controller/cards.controller.ts
  server/src/games/controller/games.controller.ts
  server/src/main.ts
  server/src/nuxt/index.ts
  server/src/nuxt/nuxt.filter.ts
  yarn.lock
Labels: enhancement
